---
title: "ENV 710: Lab 4"
author: "Firstname Lastname"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
header-includes:
 \usepackage{float}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F, eval=T, message = FALSE, fig.pos = 'H')
require(ggplot2)
require(moments)
AfrPlots <- read.csv("AfrPlots.csv")
epa <-read.csv("epa2012.csv")

```

<!-- sample code chunks included for problems, add or remove any code chunks or change the settings -->

## Problem 1


###``myqqplot`` function:
```{r myqqplot, echo=TRUE}
#my qqplot function


```


###(a) ``qqplot`` generated using ``myqqplot`` function:
  
  
```{r problem1a, fig.align='center', fig.cap="\\label{fig:figs}caption", out.width='60%'}
# Problem 1 (a) 

```
  
  
###(b) ``qqplot`` generated using ``qqnorm`` and ``qqline``:

```{r problem1b, fig.cap="\\label{fig:figs}caption", out.width='60%', fig.align='center'}
# Problem 1 (b) 


```

\newpage

## Problem 2


### (a) 

```{r problem2a, fig.cap="\\label{fig:figs}caption", out.width='70%', message=FALSE, fig.align='center'}
# Problem 2 (a) 


```

```{r problem2b, fig.cap="\\label{fig:figs}caption", out.width='60%', fig.align='center'}
# Problem 2 (b) 


```

```{r problem2c, fig.cap="\\label{fig:figs}caption", out.width="60%", fig.align='center'}
# Problem 2 (c) 

```


```{r problem2d}
# Problem 2 (d)

```
  

### (b) 

```{r problem2alog, fig.align='center', fig.cap="\\label{fig:figs}caption",out.width='70%'}
# Problem 2 (a --- log) 

```

```{r problem2blog, fig.align='center', fig.cap="\\label{fig:figs}caption",out.width='60%'}
# Problem 2 (b --- log) 


```

```{r problem2clog, fig.align='center', fig.cap="\\label{fig:figs}caption",out.width='60%'}
# Problem 2 (c --- log) 


```


```{r problem2dlog, include=FALSE}
# Problem 2 (d --- log) 

```

### (c) Conclusion

```{r problem2conclusion}
# Problem 2 (conclusion) 

```



\newpage
<!-- *** -->
<!-- Uncomment this section if you want to use an Appendix -->

<!-- 
## Appendix

```{r ref.label=knitr::all_labels(), eval=F, echo=T, message=FALSE, warning=FALSE}
```
-->